### ISSUE TITLE
RTreeError: Coordinates must not have minimums more than maximums

### ISSUE THREAD

**Issue by sherpashaky** [SEL-Columbia/networker#67]
![image](https://cloud.githubusercontent.com/assets/731717/8968566/0d5d202e-360c-11e5-8c7a-fca7f223efe6.png)

**Comment by chrisnatali** [comment]
Reproduced in dev environment (working on it)

Traceback (most recent call last):
  File "./scripts/run_networkplanner.py", line 37, in <module>
    nwk.run()
  File "/home/cjn/src/networker/networker/networkplanner_runner.py", line 90, in run
    one_based=True)
  File "/home/cjn/src/networker/networker/networker_runner.py", line 133, in build_network
    single_network=single_network)
  File "/home/cjn/src/networker/networker/networker_runner.py", line 248, in merge_network_and_nodes
    grid_with_fakes = network.project_onto(demand_nodes, rtree_index=rtree)
  File "/home/cjn/src/networker/networker/classes/geograph.py", line 126, in project_onto
    rtree_index=rtree_index)
  File "/home/cjn/src/networker/networker/classes/geograph.py", line 231, in find_nearest_edge
    candidates = rtree_index.intersection(new_bbox, objects=True)
  File "/home/cjn/miniconda/envs/networker-dev/lib/python2.7/site-packages/Rtree-0.8.1-py2.7.egg/rtree/index.py", line 434, in intersection
    if objects: return self._intersection_obj(coordinates, objects)
  File "/home/cjn/miniconda/envs/networker-dev/lib/python2.7/site-packages/Rtree-0.8.1-py2.7.egg/rtree/index.py", line 452, in _intersection_obj
    p_mins, p_maxs = self.get_coordinate_pointers(coordinates)
  File "/home/cjn/miniconda/envs/networker-dev/lib/python2.7/site-packages/Rtree-0.8.1-py2.7.egg/rtree/index.py", line 310, in get_coordinate_pointers
    raise core.RTreeError("Coordinates must not have minimums more than maximums")
rtree.core.RTreeError: Coordinates must not have minimums more than maximums

**Comment by chrisnatali** [comment]
Problem appears when existing networks have 0 length segments.  Projecting demand nodes onto 0 length segments is not handled properly.  

TODO:  
- Handle projection onto 0 length segments
- Add validation routine to Geograph to check for this (and potentially other issues) and output WARN messages

**Comment by chrisnatali** [comment]
Fixed in v0.2.3
