### ISSUE TITLE
conda build recipe not building

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/networker#75]
`conda build networker` failed on rtree dependency:
```
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import rtree
  File "/home/cjn/anaconda3/conda-bld/work/rtree/__init__.py", line 1, in <module>
    from index import Rtree
ImportError: No module named 'index'
```

Tracking here, but code is in https://github.com/SEL-Columbia/conda-recipes

**Comment by chrisnatali** [comment]
Builds via anaconda2 (i.e. python2)
